// ═══════════════════════════════════════════════════════
//   CODEX PWA — PIK-PRD API Client  (Sprint 4)
// ═══════════════════════════════════════════════════════

const PIK_BASE = 'https://pik-prd-production.up.railway.app';

// ── Types ─────────────────────────────────────────────

export type Alignment = 'ORDER' | 'VEIL' | 'WILD' | 'DARK' | 'NONE' | 'LIGHT';
export type Rarity    = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic';

export interface GearItem {
  inventory_id: string; item_id: string; item_name: string; slot: string;
  rarity: Rarity; icon: string; description: string; lore_text: string;
  modifiers: Record<string, number>; is_equipped: boolean;
  acquired_at: string; acquired_via: string;
}

export interface GearEquipment {
  weapon: GearItem | null; helm: GearItem | null; chest: GearItem | null;
  arms: GearItem | null; legs: GearItem | null; rune: GearItem | null;
}

export interface ComputedModifiers {
  xp_bonus_pct: number; boss_damage_pct: number; luck_pct: number;
  defense: number; crit_pct: number; cooldown_pct: number; fate_affinity: number;
}

export interface Gear {
  inventory: GearItem[]; equipment: GearEquipment;
  computed_modifiers: ComputedModifiers;
}

export interface HeroTitle {
  title_id: string; title_name: string; category: string;
  granted_at: string; rarity: Rarity;
}

export interface SourceLink {
  source_id: string; source_name: string; linked_at: string;
  is_active: boolean; scope: string;
}

export interface SourceProgression {
  source_id: string; source_name: string; source_type: string; sessions: number;
  xp_contributed: number; boss_kills: number; best_boss_pct: number;
  caches_granted: number; gear_acquired: number;
  first_activity: string; last_activity: string;
}

export interface FateCache {
  cache_id: string; cache_type: string; rarity: Rarity;
  status: 'opened' | 'pending'; trigger: string;
  granted_at: string; opened_at: string;
  reward: { type: string; value: string; name: string; rarity: Rarity } | null;
}

export interface ActivityEvent {
  event_id: string; event_type: string;
  payload: Record<string, unknown>; changes: Record<string, unknown> | null;
  ts: string; source_id: string | null;
}

export interface Progression {
  // Account-wide (FateAccount)
  fate_level: number; total_xp: number;
  xp_to_next_level: number; xp_in_current_level: number;
  // Character-specific (RootIdentity) — Sprint 15
  hero_level: number; hero_xp: number;
  hero_xp_in_level: number; hero_xp_to_next: number;
  sessions_completed: number; fate_markers: string[];
  titles: HeroTitle[]; equipped_title: string | null;
}

export interface NarrativeProfile {
  region: string; class: string; origin: string;
  wound: string; calling: string; virtue: string; vice: string;
}

export interface Hero {
  root_id: string; display_name: string; alignment: Alignment;
  account_type: string; created_at: string;
  progression: Progression; gear: Gear | null;
  sources: SourceLink[]; source_progression: SourceProgression[];
  fate_caches: FateCache[];
  wearable: { status: 'active' | 'expired' | 'revoked'; issued_at: string } | null;
  recent_events: ActivityEvent[]; narrative: NarrativeProfile;
}

export interface LeaderboardEntry {
  rank: number; root_id: string; display_name: string;
  alignment: Alignment; value: number; fate_level: number; sessions: number;
}

// ── Alignment ─────────────────────────────────────────

export const ALIGNMENT_COLOR: Record<string, string> = {
  ORDER: '#C8A04E', LIGHT: '#C8A04E',
  VEIL:  '#7A5888', DARK:  '#7A5888',
  WILD:  '#486E48', NONE:  '#5A4E3C', '': '#5A4E3C',
};

// ── Tiers ──────────────────────────────────────────────
export interface Tier { name: string; color: string; min: number; max: number; isJob?: boolean; }
export const TIERS: Tier[] = [
  { name: 'Bronze',     color: '#cd7f32', min: 1,  max: 6  },
  { name: 'Copper',     color: '#b87333', min: 7,  max: 13 },
  { name: 'Silver',     color: '#c0c0c0', min: 14, max: 21 },
  { name: 'Gold',       color: '#ffd700', min: 22, max: 29 },
  { name: 'Platinum',   color: '#e5e4e2', min: 30, max: 39 },
  { name: 'Adamantium', color: '#4ff0d0', min: 40, max: 40 },
  // Level 40+ — Hero has completed Adventurer progression and is eligible
  // for a Job Quest. Job Level is tracked separately (future system).
  { name: 'Job Quest',  color: '#C9A24B', min: 41, max: 999, isJob: true },
];
export function TIER_FOR_LEVEL(level: number): Tier {
  return TIERS.find(t => level >= t.min && level <= t.max) ?? TIERS[0];
}

export const ALIGNMENT_LABEL: Record<string, string> = {
  ORDER: 'ORDER', LIGHT: 'LIGHT',
  VEIL: 'VEIL',   DARK: 'DARK',
  WILD: 'WILD',   NONE: 'NONE', '': 'NONE',
};

// ── Narrative (deterministic from root_id) ────────────

const REGIONS = [
  'Wylds',
  'Kingvale',
  'Lochmaw',
  'Origin Sands',
  'Desolate Peaks',
  'Old World',
];
const CLASSES = [
  'Aegis',
  'Scalesworn',
  'Dryadic',
  'Harvester',
  'Corsair',
  'Gambler',
  'Artificer',
  'Arcane Scholar',
];
const ORIGINS = [
  'Institutional',
  'Wildborn',
  'Ruined',
  'Exiled',
  'Ancestral',
  'Erased',
  'Marginal',
  'Indentured',
  'Sheltered',
  'Militarized',
  'Devout',
  'Scholastic',
  'Mercantile',
  'Frontier',
  'Criminalized',
  'Nomadic',
  'Experimental',
  'Protected Asset',
  'Forgotten',
  'Inherited Collapse',
];
const WOUNDS = [
  'You obeyed a command that caused irreversible harm',
  'You were betrayed by the authority you trusted',
  'You enforced rules you knew were unjust',
  'You were punished for speaking the truth',
  'Advancement required sacrificing someone else',
  'You discovered the institution was hollow or corrupt',
  'You failed to protect your own',
  'Survival forced you to become cruel',
  'Strength was not enough when it mattered',
  'You trusted an outsider who destroyed something vital',
  'Civilization eradicated what you loved',
  'You crossed a moral line to survive',
  'You witnessed an atrocity and lived',
  'You survived while others did not',
  'Your actions indirectly caused destruction',
  'You tried to stop the collapse and failed',
  'You learned the truth too late',
  'You carry knowledge that should never surface',
  'You were exiled for telling the truth',
  'You took blame to protect others',
  'You were cast out to preserve comfort',
  'You left someone behind who needed you',
  'You were never allowed to explain yourself',
  'Your existence was forcibly erased to protect another',
  'You failed to live up to expectations',
  'You rejected a role chosen for you',
  'You inherited a dark truth, curse, or responsibility',
  'Your bloodline caused suffering',
  'The legacy you bear was built on lies',
  'The past demands continuation at any cost',
  'Your name was taken from you',
  'Your memories are fractured or altered',
  'Records of your existence were destroyed',
  'The truth about you is deliberately hidden',
  'You were used as a tool, not a person',
  'You know something was lost—but not what',
  'You were never fully accepted anywhere',
  'You learned invisibility as survival',
  'You were blamed because you were convenient',
  'Help was always conditional',
  'You were overlooked when it mattered most',
  'You learned not to expect justice',
  'Your freedom was purchased at another’s expense',
  'You fulfilled obligations that destroyed you',
  'You were sold to pay off another's debt',
  'Born into servitude by status, lineage, or class',
  'Your service erased your identity',
  'You escaped, but the cost follows you',
  'You were unprepared when reality arrived',
  'Others suffered while you were kept safe',
  'Protection delayed your growth',
  'Your safety came at moral cost',
  'You resent those who shielded you',
  'Violence became normal too early',
  'You failed under real combat conditions',
  'You harmed someone who trusted you',
  'Orders replaced conscience',
  'You survived when your unit did not',
  'You cannot disengage from conflict',
  'You lost faith when it mattered most',
  'You enforced belief that caused suffering',
  'You were punished for doubt',
  'Faith failed to save someone you loved',
  'You committed harm believing it righteous',
  'You fear what belief made you capable of',
  'Knowledge came without wisdom',
  'You valued truth over people—and paid for it',
  'Discovery caused harm',
  'Theory failed in practice',
  'You learned something forbidden',
  'Solely academic left you sheltered from consequence',
  'You profited from someone’s ruin',
  'Trust cost you everything',
  'You were cheated when it mattered most',
  'Survival required moral compromise',
  'You learned people are currency',
  'Wealth failed to protect what mattered',
  'Learned survival before compassion',
  'Justice was personal and inconsistent',
  'Protection required preemptive force',
  'Isolation replaced community',
  'Authority arrived only to punish',
  'Strength determined worth',
  'Guilt was presumed, not proven',
  'Punishment preceded understanding',
  'Reputation became a cage',
  'Surveillance replaced dialogue',
  'Mercy was conditional or absent',
  'Resistance became inevitable',
  'You never formed lasting bonds; jaded and closed off',
  'Leaving became easier than staying',
  'You abandoned someone without closure',
  'Home stopped meaning safety',
  'You are always passing through',
  'You don’t know where you belong',
  'You were altered without consent',
  'You survived testing others did not',
  'You were valued only for results',
  'Your pain was documented',
  'You don’t know what’s truly yours',
  'You fear what you were made into',
  'Your safety cost others their lives',
  'You were never allowed to choose',
  'Protection became imprisonment',
  'You were lied to “for your good”',
  'You failed despite preparation',
  'You resent the role imposed on you',
  'No one noticed when you needed help',
  'You learned self-reliance too early',
  'You were overlooked during crisis',
  'Absence shaped your expectations',
  'You don’t believe anyone will intervene',
  'Survival felt accidental',
  'Institutions failed before you trusted them',
  'You inherited debt, guilt, or decay',
  'Repair felt impossible',
  'Every solution was temporary',
  'You learned cynicism early',
  'Collapse became normal',
];
const CALLINGS = [
  'Protect others from similar orders',
  'Endure the burden others refuse',
  'Expose the system’s consequences',
  'Become a warning through example',
  'Restore balance to corrupted systems',
  'Uncover hidden truth',
  'Defy fate imposed by rank or law',
  'Protect others from institutional betrayal',
  'Dismantle unjust structures',
  'Protect those crushed by order',
  'Endure guilt without absolution',
  'Become a warning against obedience',
  'Uncover forgotten or buried truth',
  'Defy authority openly',
  'Endure isolation for integrity',
  'Restore balance through exposure',
  'Carry the weight of that sacrifice',
  'Protect others from similar ambition',
  'Restore balance through restraint',
  'Become a warning against ambition',
  'Expose illusion wherever it appears',
  'Defy systems that demand belief',
  'Endure without external validation',
  'Restore balance without institutions',
  'Protect others relentlessly',
  'Endure where others flee',
  'Become a warning through survival',
  'Defy weakness through strength',
  'Restore balance between survival and mercy',
  'Endure guilt without denial',
  'Protect others from becoming what you became',
  'Become a warning about survival at any cost',
  'Endure what cannot be overcome',
  'Seek balance beyond force',
  'Protect through preparation, not power',
  'Defy the belief that strength solves all',
  'Protect communities from intrusion',
  'Uncover truth before trust',
  'Endure isolation over betrayal',
  'Become a warning against naïveté',
  'Destroy the source of that harm',
  'Become a warning to encroachment',
  'Defy imposed order',
  'Protect what remains',
  'Endure the cost without justification',
  'Protect others from such choices',
  'Become a warning through honesty',
  'Become a warning the world cannot ignore',
  'Destroy the evil responsible',
  'Endure as living evidence',
  'Protect others from repetition',
  'Endure in their place',
  'Carry their memory forward',
  'Protect others so survival is not random',
  'Become a warning against complacency',
  'Restore balance through repair',
  'Destroy the forces that enabled it',
  'Become a warning against negligence',
  'Endure failure and continue',
  'Uncover why prevention failed',
  'Protect future efforts from repeating mistakes',
  'Become a warning through testimony',
  'Uncover truth before it is buried again',
  'Endure the cost of knowledge',
  'Protect others through disclosure',
  'Become a warning against delay',
  'Guard the truth from misuse',
  'Endure isolation to contain it',
  'Destroy what must not resurface',
  'Become a warning through silence or revelation',
  'Uncover truth wherever suppressed',
  'Endure exile without recanting',
  'Defy authority through persistence',
  'Become a warning against silencing',
  'Protect others at personal cost',
  'Endure injustice without surrender',
  'Restore balance through sacrifice',
  'Become a warning about misplaced loyalty',
  'Expose comfortable lies',
  'Defy social consensus',
  'Endure exclusion without apology',
  'Protect others to compensate',
  'Endure guilt without escape',
  'Carry that absence forward',
  'Become a warning about hesitation',
  'Uncover truth regardless of acceptance',
  'Endure misjudgment',
  'Defy narratives imposed on you',
  'Become a warning through action',
  'Reclaim truth and identity',
  'Defy erasure through existence',
  'Endure without recognition',
  'Become a warning against forgetting',
  'Redefine legacy',
  'Endure comparison without collapse',
  'Protect others from inherited pressure',
  'Defy prescribed destiny',
  'Defy lineage openly',
  'Restore balance between self and past',
  'Endure familial fracture',
  'Become a warning about inheritance',
  'Atone through action',
  'Endure shame without denial',
  'Protect others from repeating history',
  'Become a warning about legacy',
  'Destroy the harm tied to your name',
  'Endure hatred without retaliation',
  'Become a warning through restraint',
  'Expose the truth regardless of cost',
  'Endure collapse of identity',
  'Redefine legacy honestly',
  'Become a warning against mythmaking',
  'Defy the demand outright',
  'Endure the weight without surrender',
  'Carry the burden consciously',
  'Become a warning by refusal',
  'Reclaim identity',
  'Defy imposed anonymity',
  'Endure namelessness',
  'Become a warning against erasure',
  'Uncover the missing truth',
  'Endure uncertainty without fabrication',
  'Protect others from similar harm',
  'Restore lost truth',
  'Defy historical manipulation',
  'Endure invisibility',
  'Become a warning against revision',
  'Uncover what was concealed',
  'Endure deception without surrender',
  'Defy those who hide truth',
  'Become a warning through exposure',
  'Reclaim agency',
  'Defy instrumentalization',
  'Endure exploitation without becoming it',
  'Become a warning about utility',
  'Uncover what was taken',
  'Endure absence without invention',
  'Defy fate without full knowledge',
  'Become a warning about unseen theft',
  'Protect others pushed to the margins',
  'Endure exclusion without bitterness',
  'Restore balance through inclusion',
  'Become a warning about silent cruelty',
  'Uncover truths hidden in plain sight',
  'Endure unseen service',
  'Defy systems that ignore the unseen',
  'Become a warning through sudden presence',
  'Expose false narratives',
  'Endure injustice without internalizing it',
  'Defy scapegoating openly',
  'Protect others without conditions',
  'Endure self-reliance without isolation',
  'Restore balance through reciprocity',
  'Become a warning about transactional mercy',
  'Protect others proactively',
  'Defy neglect through action',
  'Become a warning about indifference',
  'Restore balance without trust in systems',
  'Endure reality without illusion',
  'Protect others from similar neglect',
  'Carry the weight of that price',
  'Protect others from similar bargains',
  'Become a warning about purchased freedom',
  'Endure without surrender',
  'Defy exploitative obligation',
  'Restore balance through refusal',
  'Protect others from manipulation of loyalty',
  'Endure betrayal without becoming it',
  'Defy systems that demand loyalty without return',
  'Become a warning against unchecked devotion',
  'Subvert the system from within submission',
  'Exploit invisibility to reclaim autonomy',
  'Break inherited obligation and claim self-authorship',
  'Assume responsibility where authority has failed',
  'Reclaim identity through choice',
  'Become a warning about dehumanization',
  'Endure freedom’s burden (on the run)',
  'Protect others attempting escape',
  'Restore balance by confronting the cost',
  'Become a warning about escape myths',
  'Endure hardship directly',
  'Protect others from false safety',
  'Become a warning about overprotection',
  'Carry that debt consciously',
  'Endure guilt without justification',
  'Become a warning about selective safety',
  'Endure rapid adaptation',
  'Defy artificial safety',
  'Restore balance through earned hardship',
  'Become a warning about stagnation',
  'Uncover truth before it’s buried',
  'Protect others through honesty',
  'Become a warning about delay',
  'Restore balance through accountability',
  'Endure comfort without denial',
  'Defy protection built on harm',
  'Become a warning through confession',
  'Endure resentment without acting on it',
  'Defy imposed gratitude',
  'Restore balance through independence',
  'Become a warning about control disguised as care',
  'Endure without glorifying conflict',
  'Protect others from desensitization',
  'Restore balance between force and restraint',
  'Become a warning about early indoctrination',
  'Endure failure without retreat',
  'Protect others through preparation',
  'Defy the myth of readiness',
  'Become a warning about false training',
  'Carry guilt without absolution',
  'Protect others through restraint',
  'Become a warning about obedience',
  'Defy commands that violate morality',
  'Endure discipline without obedience',
  'Restore balance through choice',
  'Become a warning about command authority',
  'Protect others so survival isn’t random',
  'Become a warning about attrition',
  'Endure peace as discipline',
  'Defy the need for battle',
  'Become a warning about perpetual war',
  'Endure doubt without replacement belief',
  'Uncover truth beyond doctrine',
  'Restore balance between faith and reality',
  'Become a warning about blind belief',
  'Atone through protection',
  'Defy imposed righteousness',
  'Defy enforced certainty',
  'Endure isolation for questioning',
  'Uncover suppressed truths',
  'Become a warning about intolerance',
  'Endure loss without bitterness',
  'Restore balance without faith’s promises',
  'Protect others through action',
  'Become a warning about expectation',
  'Carry responsibility openly',
  'Endure moral reckoning',
  'Restore balance through reparations',
  'Become a warning against moral certainty',
  'Endure without rejecting belief entirely',
  'Defy extremes of devotion',
  'Restore balance through humility',
  'Become a warning about unchecked faith',
  'Restore balance through application',
  'Endure consequences of ignorance',
  'Protect others from abstraction',
  'Become a warning about detached intellect',
  'Endure relational loss',
  'Restore balance between truth and harm',
  'Protect others from cold reasoning',
  'Become a warning about moral calculus',
  'Take responsibility for outcomes',
  'Endure guilt without suppression',
  'Destroy what should not exist',
  'Become a warning about unchecked inquiry',
  'Endure humility',
  'Restore balance through experience',
  'Protect others through testing',
  'Become a warning about assumption',
  'Guard truth from misuse',
  'Destroy what cannot be controlled',
  'Become a warning through silence',
  'Endure accountability',
  'Defy insulation',
  'Become a warning about privilege',
  'Restore balance through restitution',
  'Protect others from exploitation',
  'Become a warning about profit',
  'Endure without cynicism',
  'Protect others through caution',
  'Restore balance between trust and leverage',
  'Become a warning about naïveté',
  'Defy unfair systems',
  'Endure loss without collapse',
  'Restore balance through transparency',
  'Become a warning about predation',
  'Endure moral ambiguity',
  'Restore balance through later choice',
  'Protect others from similar compromise',
  'Become a warning about necessity',
  'Defy transactional relationships',
  'Endure isolation from sincerity',
  'Restore balance through loyalty',
  'Become a warning about commodification',
  'Endure vulnerability',
  'Restore balance beyond material power',
  'Protect others through presence',
  'Become a warning about false security',
  'Prioritize endurance over empathy',
  'Protect only what is proven valuable',
  'Relearn mercy without sacrificing strength',
  'Become a guardian who tempers survival with care',
  'Enforce personal rules in absence of law',
  'Retaliate to establish deterrence',
  'Impose consistent consequence',
  'Become the standard others submit to',
  'Strike before threats fully form',
  'Normalize violence as prevention',
  'Master restraint without vulnerability',
  'Become a shield rather than a weapon',
  'Depend on solitude for survival',
  'Form temporary alliances of convenience',
  'Build chosen bonds intentionally',
  'Create a community others rally around',
  'Avoid authority entirely',
  'Sabotage external control',
  'Challenge legitimacy openly',
  'Establish autonomous order',
  'Prove value through dominance',
  'Respect only visible power',
  'Redefine strength beyond force',
  'Elevate others through earned resilience',
  'Act as if judgment is inevitable',
  'Conceal intent and action',
  'Confront accusation directly',
  'Become evidence of injustice',
  'Harden against authority response',
  'Anticipate and outmaneuver control',
  'Demand due reckoning',
  'Reshape systems to prevent repetition',
  'Accept the imposed identity',
  'Manipulate expectation for advantage',
  'Break the narrative through action',
  'Define identity beyond accusation',
  'Operate unseen whenever possible',
  'Feed false patterns to observers',
  'Force confrontation into the open',
  'Turn scrutiny into accountability',
  'Expect none and offer none',
  'Trade mercy as currency',
  'Choose compassion as defiance',
  'Become a source of mercy others rely on',
  'Resist quietly to survive',
  'Escalate opposition strategically',
  'Lead organized defiance',
  'Transform resistance into legitimacy',
  'Endure solitude without collapse',
  'Protect others briefly but fully',
  'Restore balance through presence',
  'Become a warning about impermanence',
  'Endure commitment',
  'Defy flight instinct',
  'Restore balance through rooted choice',
  'Become a warning about avoidance',
  'Carry guilt without erasure',
  'Protect others from similar loss',
  'Restore balance through return',
  'Become a warning about departure',
  'Endure instability',
  'Protect others through vigilance',
  'Restore balance through mobility',
  'Become a warning about false refuge',
  'Endure transience',
  'Restore balance without permanence',
  'Protect others temporarily',
  'Become a warning about attachment',
  'Uncover where you belong',
  'Endure without definition',
  'Defy identity by place',
  'Become a warning about rootlessness',
  'Endure the change consciously',
  'Destroy what enables such harm',
  'Become a warning about experimentation',
  'Endure survival guilt',
  'Become a warning about ambition',
  'Reclaim personhood',
  'Endure objectification',
  'Endure without spectacle',
  'Expose those records',
  'Uncover authentic self',
  'Endure uncertainty',
  'Defy imposed identity',
  'Become a warning about ownership',
  'Endure without denial',
  'Destroy what made you',
  'Restore balance through control',
  'Become a warning about creation',
  'Endure guilt without refusal',
  'Protect others at your own risk',
  'Become a warning about sacrifice',
  'Endure imposed destiny',
  'Defy caretakers',
  'Become a warning about control',
  'Endure confinement without collapse',
  'Defy protective authority',
  'Restore balance through escape',
  'Become a warning about safety',
  'Uncover full truth',
  'Endure betrayal without retreat',
  'Become a warning about paternalism',
  'Endure inadequacy',
  'Restore balance beyond preparation',
  'Protect others through humility',
  'Become a warning about planning',
  'Defy expectation',
  'Endure role without acceptance',
  'Restore balance through redefinition',
  'Become a warning about destiny',
  'Protect others who are unseen',
  'Become a warning about neglect',
  'Endure independence',
  'Protect others through support',
  'Restore balance through trust',
  'Become a warning about abandonment',
  'Endure without bitterness',
  'Protect others preemptively',
  'Become a warning about apathy',
  'Endure without expectation',
  'Restore balance through realism',
  'Protect others pragmatically',
  'Become a warning about absence',
  'Endure without hope',
  'Protect others despite doubt',
  'Restore balance through action',
  'Become a warning about reliance',
  'Endure existence consciously',
  'Restore balance through intention',
  'Protect others deliberately',
  'Become a warning about chance',
  'Defy reliance on systems',
  'Restore balance through alternatives',
  'Become a warning about decay',
  'Carry responsibility consciously',
  'Endure obligation',
  'Restore balance through resolution',
  'Endure without hope of repair',
  'Defy inevitability',
  'Restore balance in fragments',
  'Become a warning about despair',
  'Endure impermanence',
  'Restore balance repeatedly',
  'Become a warning about short-term fixes',
  'Endure realism without cruelty',
  'Defy nihilism',
  'Become a warning about surrender',
  'Endure normalization of decay',
  'Restore balance despite futility',
  'Protect others from apathy',
  'Become a warning about acceptance',
];
const VIRTUES = [
  'Responsibility',
  'Fortitude',
  'Accountability',
  'Moral Courage',
  'Justice',
  'Integrity',
  'Self-Determination',
  'Guardianship',
  'Reform',
  'Compassion',
  'Conscientious Dissent',
  'Truthfulness',
  'Courage',
  'Moral Resolve',
  'Transparency',
  'Stewardship',
  'Temperance',
  'Humility',
  'Discernment',
  'Independence',
  'Self-Reliance',
  'Adaptability',
  'Resolve',
  'Testimony',
  'Empowerment',
  'Mercy',
  'Honesty',
  'Preventative Care',
  'Ethical Witness',
  'Acceptance',
  'Wisdom',
  'Prudence',
  'Loyalty',
  'Caution',
  'Retributive Justice',
  'Boundary-Keeping',
  'Autonomy',
  'Preservation',
  'Guidance',
  'Moral Witness',
  'Righteous Resolve',
  'Endurance',
  'Sacrificial Fortitude',
  'Remembrance',
  'Vigilance',
  'Restoration',
  'Structural Justice',
  'Perseverance',
  'Causal Insight',
  'Truth Vigilance',
  'Intellectual Courage',
  'Urgency',
  'Containment Discipline',
  'Protective Finality',
  'Moral Judgment',
  'Investigative Integrity',
  'Conviction',
  'Tenacity',
  'Free Expression',
  'Altruism',
  'Moral Resilience',
  'Redemptive Sacrifice',
  'Ethical Loyalty',
  'Independent Thought',
  'Self-Respect',
  'Wakefulness',
  'Reparative Care',
  'Moral Ownership',
  'Commemorative Duty',
  'Decisiveness',
  'Patience',
  'Self-Authorship',
  'Exemplarity',
  'Self-Realization',
  'Existential Assertion',
  'Quiet Dignity',
  'Transformative Vision',
  'Self-Confidence',
  'Intergenerational Care',
  'Integration',
  'Emotional Endurance',
  'Cautionary Stewardship',
  'Restorative Justice',
  'Preventative Wisdom',
  'Moral Memory',
  'Cleansing Resolve',
  'Reparative Justice',
  'Forbearance',
  'Radical Honesty',
  'Psychological Resilience',
  'Authenticity',
  'Narrative Integrity',
  'Moral Refusal',
  'Steadfastness',
  'Deliberate Responsibility',
  'Principled Resistance',
  'Self-Ownership',
  'Assertiveness',
  'Inner Stability',
  'Existential Defense',
  'Investigative Persistence',
  'Intellectual Humility',
  'Safeguarding',
  'Testimonial Strength',
  'Historical Repair',
  'Archival Integrity',
  'Quiet Endurance',
  'Historical Fidelity',
  'Inner Resolve',
  'Public Accountability',
  'Personal Dignity',
  'Moral Endurance',
  'Humanization',
  'Restorative Truth-Seeking',
  'Existential Honesty',
  'Courageous Uncertainty',
  'Moral Alertness',
  'Advocacy',
  'Equity',
  'Social Conscience',
  'Perceptive Insight',
  'Quiet Devotion',
  'Structural Awareness',
  'Assertive Visibility',
  'Moral Bravery',
  'Unconditional Care',
  'Independent Stability',
  'Mutuality',
  'Ethical Altruism',
  'Anticipatory Care',
  'Initiative',
  'Moral Sensitivity',
  'Pragmatic Justice',
  'Grounded Realism',
  'Attentive Guardianship',
  'Protective Prudence',
  'Honest Accountability',
  'Ethical Awareness',
  'Ethical Refusal',
  'Principled Boundary-Setting',
  'Existential Proof',
  'Moral Containment',
  'Reciprocal Justice',
  'Measured Allegiance',
  'Strategic Patience',
  'Adaptive Cunning',
  'Civic Responsibility',
  'Inner Worth',
  'Personal Sovereignty',
  'Human Dignity',
  'Self-Reliant Courage',
  'Liberative Care',
  'Ethical Reckoning',
  'Reality Witness',
  'Grit',
  'Protective Realism',
  'Corrective Transparency',
  'Autonomy Advocacy',
  'Moral Indebtedness',
  'Moral Honesty',
  'Ethical Consistency',
  'Adaptive Resilience',
  'Authentic Courage',
  'Earned Wisdom',
  'Growth Orientation',
  'Preventative Truth-Seeking',
  'Ethical Transparency',
  'Decisive Urgency',
  'Moral Rectitude',
  'Grounded Gratitude',
  'Ethical Resistance',
  'Confessional Integrity',
  'Emotional Discipline',
  'Autonomous Balance',
  'Boundary Awareness',
  'Peace Discipline',
  'Empathic Guarding',
  'Martial Temperance',
  'Critical Awareness',
  'Readiness',
  'Adaptive Humility',
  'Experiential Honesty',
  'Moral Accountability',
  'Ethical Control',
  'Just Stewardship',
  'Ethical Autonomy',
  'Internal Discipline',
  'Deliberate Agency',
  'Power Awareness',
  'Strategic Vigilance',
  'Pacified Strength',
  'Conflict Discernment',
  'Anti-War Witness',
  'Transcendent Inquiry',
  'Integrative Wisdom',
  'Critical Faith',
  'Redemptive Care',
  'Honest Reckoning',
  'Moral Independence',
  'Open Inquiry',
  'Investigative Courage',
  'Pluralistic Defense',
  'Grace',
  'Secular Hope',
  'Practical Compassion',
  'Realistic Acceptance',
  'Transparent Accountability',
  'Ethical Fortitude',
  'Epistemic Humility',
  'Balanced Faith',
  'Moderation',
  'Grounded Humility',
  'Faithful Skepticism',
  'Applied Wisdom',
  'Learning Resilience',
  'Human-Centered Reason',
  'Embodied Insight',
  'Ethical Calibration',
  'Compassionate Judgment',
  'Humanistic Ethics',
  'Ownership',
  'Honest Self-Assessment',
  'Epistemic Responsibility',
  'Self-Awareness',
  'Experiential Wisdom',
  'Restraint',
  'Ethical Courage',
  'Equity Awareness',
  'Ethical Stewardship',
  'Hopeful Realism',
  'Careful Guardianship',
  'Relational Wisdom',
  'Justice-Seeking',
  'Resilience',
  'Open Accountability',
  'Protective Awareness',
  'Ethical Tolerance',
  'Reflective Agency',
  'Preventative Integrity',
  'Contextual Wisdom',
  'Relational Integrity',
  'Self-Containment',
  'Faithfulness',
  'Human-Centered Ethics',
  'Courageous Openness',
  'Value Reorientation',
  'Attentive Care',
  'Reality Awareness',
  'Stoic Resolve',
  'Strategic Preservation',
  'Tempered Compassion',
  'Balanced Guardianship',
  'Self-Governance',
  'Protective Retaliation',
  'Exemplary Leadership',
  'Preventative Action',
  'Security Prioritization',
  'Disciplined Control',
  'Defensive Altruism',
  'Self-Sufficiency',
  'Tactical Cooperation',
  'Intentional Belonging',
  'Communal Leadership',
  'Resistance',
  'Civic Courage',
  'Self-Rule',
  'Assertive Strength',
  'Pragmatic Realism',
  'Expansive Strength',
  'Moral Preparedness',
  'Strategic Discretion',
  'Transparent Defense',
  'Embodied Testimony',
  'Psychological Armor',
  'Strategic Foresight',
  'Procedural Justice',
  'Structural Reform',
  'Adaptive Acceptance',
  'Social Intelligence',
  'Self-Definition',
  'Tactical Stealth',
  'Counterintelligence',
  'Directness',
  'Public Rectification',
  'Radical Self-Reliance',
  'Strategic Mercy',
  'Defiant Compassion',
  'Reliable Benevolence',
  'Subtle Endurance',
  'Calculated Resistance',
  'Collective Leadership',
  'Institutionalized Dissent',
  'Focused Altruism',
  'Grounded Presence',
  'Fidelity',
  'Courageous Staying',
  'Intentional Grounding',
  'Moral Continuity',
  'Reparative Presence',
  'Commitment Awareness',
  'Flexible Stability',
  'Shelter Discernment',
  'Existential Acceptance',
  'Adaptive Continuity',
  'Situational Care',
  'Relational Awareness',
  'Self-Discovery',
  'Inner Coherence',
  'Grounded Insight',
  'Mindful Adaptation',
  'Ethical Caution',
  'Tempered Aspiration',
  'Psychological Endurance',
  'Quiet Integrity',
  'Archival Justice',
  'Moral Stewardship',
  'Witnessed Truth',
  'Existential Autonomy',
  'Honest Acceptance',
  'Transformative Resolve',
  'Disciplined Order',
  'Creative Responsibility',
  'Courageous Altruism',
  'Autonomy Assertion',
  'Mental Fortitude',
  'Liberative Action',
  'Risk Discernment',
  'Emotional Resilience',
  'Agency Advocacy',
  'Adaptive Wisdom',
  'Servant Leadership',
  'Inner Separation',
  'Transformative Agency',
  'Existential Choice',
  'Grounded Care',
  'Relational Care',
  'Mutual Confidence',
  'Attachment Awareness',
  'Moral Wakefulness',
  'Radical Acceptance',
  'Grounded Pragmatism',
  'Practical Care',
  'Presence Awareness',
  'Existential Fortitude',
  'Faithful Action',
  'Decisive Engagement',
  'Mindful Presence',
  'Purposeful Action',
  'Intentional Guardianship',
  'Preparedness',
  'Adaptive Autonomy',
  'Creative Problem-Solving',
  'Preservation Awareness',
  'Deliberate Ownership',
  'Duty',
  'Closure',
  'Intergenerational Awareness',
  'Stoic Acceptance',
  'Defiant Hope',
  'Incremental Repair',
  'Existential Witness',
  'Persistent Care',
  'Long-Term Thinking',
  'Compassionate Realism',
  'Meaning-Making',
  'Ethical Engagement',
  'Wakeful Endurance',
  'Faithful Persistence',
  'Moral Stimulation',
];
const VICES = [
  'Authoritarian Control',
  'Silent Martyrdom',
  'Obsessive Revelation',
  'Self-Destructive Exemplarity',
  'Institutional Rigidity',
  'Compulsive Disclosure',
  'Reflexive Defiance',
  'Chronic Distrust',
  'Destructive Zeal',
  'Overextension',
  'Self-Punishment',
  'Contempt for Authority',
  'Historical Fixation',
  'Provocation',
  'Withdrawal',
  'Reductionism',
  'Survivor’s Guilt',
  'Suppression of Aspiration',
  'Paralysis',
  'Fear of Growth',
  'Cynicism',
  'Rejection of Structure',
  'Emotional Isolation',
  'Anti-Order Bias',
  'Smothering Control',
  'Reckless Endurance',
  'Trauma Identity',
  'Dominance',
  'Moral Rationalization',
  'Self-Flagellation',
  'Projection',
  'Absolutism',
  'Resignation',
  'Indecision',
  'Control Fixation',
  'Power Aversion',
  'Exclusion',
  'Suspicion',
  'Alienation',
  'Vengeance',
  'Hostility',
  'Anarchic Impulse',
  'Stagnation',
  'Self-Damnation',
  'Inhibition',
  'Paternalism',
  'Brutal Candor',
  'Self-Immolation',
  'Vengeful Fixation',
  'Identity Entrapment',
  'Overcorrection',
  'Inability to Move On',
  'Control Obsession',
  'Alarmism',
  'Compulsive Fixing',
  'Totalizing Blame',
  'Perfectionism',
  'Emotional Suppression',
  'Retrospective Fixation',
  'Risk Aversion',
  'Trauma Reenactment',
  'Obsessive Urgency',
  'Reckless Disclosure',
  'Impulsiveness',
  'Gatekeeping Absolutism',
  'Emotional Withdrawal',
  'Erasure Absolutism',
  'Extremism',
  'Relentless Exposure',
  'Bitterness',
  'Insubordination Spiral',
  'Self-Erasure',
  'Hardness of Heart',
  'Martyr Complex',
  'Distrust of Bonds',
  'Social Alienation',
  'Contrarianism',
  'Emotional Detachment',
  'Chronic Discontent',
  'Guilt-Driven Control',
  'Emotional Entrapment',
  'Identity Anchored to Loss',
  'Impulsivity',
  'Social Disregard',
  'Isolation',
  'Reckless Symbolism',
  'Identity Fixation',
  'Performative Defiance',
  'Learned Invisibility',
  'Obsession with Memory',
  'Legacy Fixation',
  'Defensive Pride',
  'Overprotection',
  'Rejection of Guidance',
  'Familial Severance',
  'Historical Relativism',
  'Emotional Numbing',
  'Lineage Aversion',
  'Endless Self-Penitence',
  'Self-Loathing',
  'Historical Rigidity',
  'Inherited Guilt Projection',
  'Total Self-Rejection',
  'Suppressed Rage',
  'Emotional Repression',
  'Burn-the-World Transparency',
  'Dissociation',
  'Brutal Self-Revisionism',
  'Cynical Deconstruction',
  'Stubbornness',
  'Overidentification',
  'Negation of Compromise',
  'Identity Obsession',
  'Aggressive Visibility',
  'Detachment from Self',
  'Obsession',
  'Overcontrol',
  'Revisionist Rigidity',
  'Temporal Absolutism',
  'Learned Helplessness',
  'Resistance to Growth',
  'Obsessive Unmasking',
  'Chronic Suspicion',
  'Hostile Exposure',
  'Scorched-Reputation Tactics',
  'Hyper-Independence',
  'Rejection of Cooperation',
  'Anti-Utility Absolutism',
  'Consuming Retrieval',
  'Emotional Hollowing',
  'Reckless Defiance',
  'Paranoia',
  'Savior Complex',
  'Forced Inclusion',
  'Moral Condemnation',
  'Pattern Obsession',
  'Institutional Hostility',
  'Disruptive Shock Tactics',
  'Combative Truth-Telling',
  'Confrontational Identity',
  'Trauma Anchoring',
  'Boundary Erosion',
  'Refusal of Support',
  'Transaction Avoidance',
  'Moral Absolutism',
  'Overmanagement',
  'Compulsive Intervention',
  'Institutional Cynicism',
  'Emotional Starkness',
  'Hypervigilance',
  'Guilt Fixation',
  'Restrictive Control',
  'Anti-Compromise Rigidity',
  'Total Noncompliance',
  'Negationism',
  'Distrust of Commitment',
  'Institutional Rejection',
  'Relational Cynicism',
  'Manipulative Compliance',
  'Identity Fragmentation',
  'Root Severance',
  'Authority Replacement',
  'External Disengagement',
  'Anti-Utility Extremism',
  'Moral Rigidity',
  'Chronic Flight',
  'Punitive Self-Judgment',
  'Hope Suppression',
  'Masochistic Endurance',
  'Safety Nihilism',
  'Overexposure',
  'Anti-Care Bias',
  'Debt Identity',
  'Self-Condemnation',
  'Rigid Fairness',
  'Burnout',
  'Risk-Seeking',
  'Gatekeeping Hardship',
  'Chronic Dissatisfaction',
  'Harmful Bluntness',
  'Punitive Fixation',
  'Moral Complacency',
  'Total Rejection of Care',
  'Self-Exposure Harm',
  'Ingratitude',
  'Isolationism',
  'Anti-Care Absolutism',
  'Conflict Aversion',
  'Moral Fragility',
  'Hesitation',
  'Institutional Distrust',
  'Overplanning',
  'Anti-Preparation Bias',
  'Training Cynicism',
  'Emotional Withholding',
  'Moral Authoritarianism',
  'Defiant Identity',
  'Rigidity',
  'Decision Paralysis',
  'Authority Rejection',
  'Inability to Release',
  'Fatalism',
  'Restlessness',
  'Avoidance',
  'Militaristic Cynicism',
  'Existential Drift',
  'Anti-Tradition Bias',
  'Compartmentalization',
  'Cynical Disbelief',
  'Ethical Isolation',
  'Public Self-Destruction',
  'Perpetual Doubt',
  'Relentless Digging',
  'Reactionary Opposition',
  'Spiritual Rejection',
  'Self-Blame',
  'Internal Collapse',
  'Endless Atonement',
  'Moral Relativism',
  'Cognitive Dissonance',
  'Lukewarm Conviction',
  'Self-Minimization',
  'Spiritual Cynicism',
  'Shame Anchoring',
  'Anti-Theory Bias',
  'Intellectual Distrust',
  'Attachment Avoidance',
  'Moral Calculation',
  'Sentimental Bias',
  'Anti-Utilitarian Rigidity',
  'Rumination',
  'Absolutist Erasure',
  'Knowledge Suppression',
  'Self-Doubt',
  'Disdain for Theory',
  'Gatekeeping',
  'Distrust of Intuition',
  'Moral Withholding',
  'Reckless Exposure',
  'Class Resentment',
  'Endless Compensation',
  'Anti-Commerce Rigidity',
  'Naïve Optimism',
  'Excessive Risk Aversion',
  'Strategic Detachment',
  'Privacy Erosion',
  'Moral Drift',
  'Decision Avoidance',
  'Moral Policing',
  'Rejection of Reciprocity',
  'Emotional Distance',
  'Ingroup Bias',
  'Anti-Market Dogmatism',
  'Emotional Exposure',
  'Material Rejection',
  'Self-Neglect',
  'Security Nihilism',
  'Emotional Callousness',
  'Conditional Worth',
  'Hesitant Mercy',
  'Overburdened Protector',
  'Vigilantism',
  'Escalatory Violence',
  'Authoritarianism',
  'Preemptive Aggression',
  'Desensitization',
  'Emotional Sealing',
  'Passive Enabling',
  'Social Withdrawal',
  'Instrumentalization',
  'Exclusivity',
  'Cult of Personality',
  'Anomie',
  'Destabilization',
  'Perpetual Opposition',
  'Fragmentation',
  'Tyranny',
  'Power Worship',
  'Rejection of Might',
  'Trial-by-Fire Elitism',
  'Deception',
  'Combative Honesty',
  'Manipulation',
  'Retributive Fixation',
  'Overengineering',
  'Internalized Oppression',
  'Cynical Manipulation',
  'Deception Dependency',
  'Escalation',
  'Performative Exposure',
  'Emotional Severance',
  'Moral Transactionalism',
  'Self-Sacrifice Extremism',
  'Compassion Fatigue',
  'Instrumental Conflict',
  'Polarization',
  'Bureaucratized Rebellion',
  'Disposable Relationships',
  'Overattachment',
  'Nihilism',
  'Stubborn Attachment',
  'Inflexibility',
  'Shame-Based Judgment',
  'Identity Guilt',
  'Regression',
  'Fear of Change',
  'Chronic Anxiety',
  'Rootlessness',
  'Distrust of Safety',
  'Detachment',
  'Lack of Commitment',
  'Avoidance of Responsibility',
  'Identity Diffusion',
  'Fear of Innovation',
  'Invisibility',
  'Vindictive Transparency',
  'Narcissistic Introspection',
  'Possessiveness',
  'Fear of Origin',
  'Self-Endangerment',
  'Defiant Isolation',
  'Rejection of Support',
  'Authority Aversion',
  'Recklessness',
  'Obsessive Disclosure',
  'Trust Erosion',
  'Exposure Harm',
  'Anti-Care Extremism',
  'Anti-Planning Bias',
  'Reactionary Identity',
  'Identity Drift',
  'Dependence',
  'Naïveté',
  'Fear of Commitment',
  'Passivity',
  'Existential Anxiety',
  'Despair',
  'Relational Severance',
  'Pessimism',
  'Resentment',
  'Premature Finality',
  'Determinism',
  'Delusion',
  'Incompletion',
  'Exhaustion',
  'Reform Paralysis',
  'Emotional Hardness',
  'Idealism',
  'Self-Depletion',
  'Resistance to Peace',
];

function seededIndex(seed: string, offset: number, len: number): number {
  let h = offset * 2654435761;
  for (let i = 0; i < seed.length; i++) h = Math.imul(h ^ seed.charCodeAt(i), 2654435761);
  return Math.abs(h) % len;
}

export function generateNarrative(rootId: string): NarrativeProfile {
  const s = rootId.replace(/-/g, '');
  return {
    region:  REGIONS [seededIndex(s, 0, REGIONS.length)],
    class:   CLASSES [seededIndex(s, 1, CLASSES.length)],
    origin:  ORIGINS [seededIndex(s, 2, ORIGINS.length)],
    wound:   WOUNDS  [seededIndex(s, 3, WOUNDS.length)],
    calling: CALLINGS[seededIndex(s, 4, CALLINGS.length)],
    virtue:  VIRTUES [seededIndex(s, 5, VIRTUES.length)],
    vice:    VICES   [seededIndex(s, 6, VICES.length)],
  };
}

// ── Mappers ───────────────────────────────────────────

function mapListRow(r: Record<string, unknown>): Hero {
  const rootId = r.root_id as string;
  return {
    root_id: rootId, display_name: (r.hero_name ?? 'Unknown Hero') as string,
    alignment: ((r.fate_alignment as string) || 'NONE') as Alignment,
    account_type: 'registered', created_at: '',
    progression: {
      fate_level: (r.fate_level ?? 1) as number, total_xp: (r.fate_xp ?? 0) as number,
      xp_to_next_level: 0, xp_in_current_level: 0, sessions_completed: 0,
      fate_markers: [], titles: [], equipped_title: null,
    },
    gear: null, sources: [], source_progression: [], fate_caches: [],
    wearable: null, recent_events: [], narrative: generateNarrative(rootId),
  };
}

function mapTitle(t: Record<string, unknown>): HeroTitle {
  return {
    title_id:   (t.title_id ?? '') as string,
    title_name: (t.display_name ?? t.title_name ?? t.title_id ?? '') as string,
    category:   (t.category ?? 'general') as string,
    granted_at: (t.granted_at ?? '') as string,
    rarity:     'rare' as Rarity,
  };
}

function mapGearItem(g: Record<string, unknown>): GearItem {
  return {
    inventory_id: (g.inventory_id ?? '') as string,
    item_id:      (g.item_id ?? '') as string,
    item_name:    (g.item_name ?? '') as string,
    slot:         (g.slot ?? '') as string,
    rarity:       (g.rarity ?? 'common') as Rarity,
    icon:         (g.icon ?? '⚔') as string,
    description:  (g.description ?? '') as string,
    lore_text:    (g.lore_text ?? '') as string,
    modifiers:    (g.modifiers ?? {}) as Record<string, number>,
    is_equipped:  (g.is_equipped ?? false) as boolean,
    acquired_at:  (g.acquired_at ?? '') as string,
    acquired_via: (g.acquired_via ?? '') as string,
  };
}

function mapGear(raw: Record<string, unknown>): Gear {
  // Full data lives in inventory; equipment slots only have partial data.
  // Enrich equipment slots by looking up matching inventory_id.
  const inv = ((raw.inventory ?? []) as Record<string, unknown>[]).map(mapGearItem);
  const invMap = new Map(inv.map(i => [i.inventory_id, i]));

  const eq = (raw.equipment ?? {}) as Record<string, unknown>;
  const enrichSlot = (s: unknown): GearItem | null => {
    if (!s) return null;
    const partial = s as Record<string, unknown>;
    const full = invMap.get(partial.inventory_id as string);
    return full ?? mapGearItem(partial);
  };

  return {
    inventory: inv,
    equipment: {
      weapon: enrichSlot(eq.weapon), helm:  enrichSlot(eq.helm),
      chest:  enrichSlot(eq.chest),  arms:  enrichSlot(eq.arms),
      legs:   enrichSlot(eq.legs),   rune:  enrichSlot(eq.rune),
    },
    computed_modifiers: (raw.computed_modifiers ?? {
      xp_bonus_pct: 0, boss_damage_pct: 0, luck_pct: 0,
      defense: 0, crit_pct: 0, cooldown_pct: 0, fate_affinity: 0,
    }) as ComputedModifiers,
  };
}

function mapFateCache(c: Record<string, unknown>): FateCache {
  const reward = c.reward as Record<string, unknown> | null;
  return {
    cache_id:   (c.cache_id ?? '') as string,
    cache_type: (c.cache_type ?? '') as string,
    rarity:     (c.rarity ?? 'common') as Rarity,
    status:     (c.status ?? 'opened') as 'opened' | 'pending',
    trigger:    (c.trigger ?? '') as string,
    granted_at: (c.granted_at ?? '') as string,
    opened_at:  (c.opened_at ?? '') as string,
    reward: reward ? {
      type:   (reward.type ?? '') as string,
      value:  (reward.value ?? '') as string,
      name:   (reward.name ?? '') as string,
      rarity: (reward.rarity ?? 'common') as Rarity,
    } : null,
  };
}

function mapFullUser(r: Record<string, unknown>): Hero {
  const identity  = (r.identity  ?? {}) as Record<string, unknown>;
  const persona   = (r.persona   ?? {}) as Record<string, unknown>;
  const prog      = (r.progression ?? {}) as Record<string, unknown>;
  const links     = (r.source_links ?? []) as Record<string, unknown>[];
  const srcProg   = (r.source_progression ?? []) as Record<string, unknown>[];
  const events    = (r.recent_events ?? []) as Record<string, unknown>[];
  const wearables = (r.wearables ?? []) as Record<string, unknown>[];
  const caches    = (r.fate_caches ?? []) as Record<string, unknown>[];
  const rawGear   = r.gear as Record<string, unknown> | null;
  const rootId    = identity.root_id as string;

  const titlesDetail = (prog.titles_detail ?? []) as Record<string, unknown>[];
  const titlesRaw    = (prog.titles ?? []) as unknown[];
  const titles: HeroTitle[] = titlesDetail.length > 0
    ? titlesDetail.map(mapTitle)
    : titlesRaw.map(t => typeof t === 'string'
        ? { title_id: t, title_name: t.replace(/^title_/,'').replace(/_/g,' ').replace(/\b\w/g, c => c.toUpperCase()), category: 'general', granted_at: '', rarity: 'rare' as Rarity }
        : mapTitle(t as Record<string, unknown>));

  const activeWearable = wearables.find(w => w.status === 'active');

  // ── Hero XP (character-specific) — Sprint 15/16 ──────────────────────────
  // hero_xp / hero_level come from root_identities (added Sprint 15).
  // The backend identity service returns them in progression.hero_xp/hero_level
  // after the Sprint 16 identity service patch. Falls back to fate_xp/fate_level
  // (the values from before the split) so old sessions still work.
  const heroXpRaw  = (prog.hero_xp   ?? identity.hero_xp   ?? (prog.fate_xp   ?? 0)) as number;
  const heroLvRaw  = (prog.hero_level ?? identity.hero_level ?? (prog.fate_level ?? 1)) as number;

  // ── Fate XP (account-wide) — Sprint 16 ───────────────────────────────────
  // fate_xp / fate_level on the progression object now come from fate_accounts
  // (the account-wide sum) after the Sprint 16 identity service patch.
  // Before the patch, fate_xp equals the hero's individual XP — in that case
  // fall back to heroXp so both bars show something meaningful.
  const fateXpRaw = (prog.fate_xp   ?? heroXpRaw) as number;
  const fateLvRaw = (prog.fate_level ?? heroLvRaw) as number;

  // XP within current level and XP needed to next — prefer values from backend,
  // then compute a best-effort estimate (linear 500 xp/level fallback).
  const fateInLvl  = (prog.xp_in_current_level ?? Math.max(0, fateXpRaw - (fateLvRaw - 1) * 500)) as number;
  const fateToNext = (prog.xp_needed_for_next  ?? 500) as number;

  // Hero-level progress within current level (linear 500 xp/level fallback
  // until backend returns hero_xp_in_level)
  const heroInLvl  = (prog.hero_xp_in_level ?? Math.max(0, heroXpRaw - (heroLvRaw - 1) * 500)) as number;
  const heroToNext = (prog.hero_xp_to_next  ?? 500) as number;

  return {
    root_id:      rootId,
    display_name: (persona.hero_name ?? persona.display_name ?? 'Unknown Hero') as string,
    alignment:    ((persona.fate_alignment as string) || 'NONE') as Alignment,
    account_type: (identity.status ?? 'registered') as string,
    created_at:   (identity.enrolled_at ?? '') as string,
    progression: {
      fate_level:          fateLvRaw,
      total_xp:            fateXpRaw,
      xp_to_next_level:    fateToNext,
      xp_in_current_level: fateInLvl,
      hero_level:          heroLvRaw,
      hero_xp:             heroXpRaw,
      hero_xp_in_level:    heroInLvl,
      hero_xp_to_next:     heroToNext,
      // Use total_sessions from progression object (authoritative)
      sessions_completed:  (prog.total_sessions ?? srcProg.reduce((a, s) => a + ((s.sessions as number) ?? 0), 0)) as number,
      fate_markers:        (prog.fate_markers ?? []) as string[],
      titles,
      equipped_title:      (persona.equipped_title ?? null) as string | null,
    },
    gear: rawGear ? mapGear(rawGear) : null,
    fate_caches: caches.map(mapFateCache),
    sources: links.map(l => ({
      source_id:   l.source_id as string,
      source_name: (l.source_name ?? l.source_id) as string,
      linked_at:   (l.granted_at ?? '') as string,
      is_active:   l.status === 'active',
      scope:       (l.scope ?? '') as string,
    })),
    source_progression: srcProg.map(s => ({
      source_id:      s.source_id as string,
      source_name:    (s.source_name ?? s.source_id) as string,
      sessions:       (s.sessions ?? 0) as number,
      xp_contributed: (s.xp_contributed ?? 0) as number,
      boss_kills:     (s.boss_kills ?? 0) as number,
      best_boss_pct:  (s.best_boss_pct ?? 0) as number,
      caches_granted: (s.caches_granted ?? 0) as number,
      gear_acquired:  (s.gear_acquired ?? 0) as number,
      first_activity: (s.first_activity ?? '') as string,
      last_activity:  (s.last_activity ?? '') as string,
    })),
    wearable: activeWearable
      ? { status: activeWearable.status as 'active', issued_at: (activeWearable.issued_at ?? '') as string }
      : null,
    recent_events: events.map(e => ({
      event_id:   (e.event_id ?? String(Math.random())) as string,
      event_type: (e.event_type ?? 'unknown') as string,
      payload:    (e.payload ?? {}) as Record<string, unknown>,
      changes:    (e.changes ?? null) as Record<string, unknown> | null,
      ts:         (e.created_at ?? '') as string,
      source_id:  (e.source_id ?? null) as string | null,
    })),
    narrative: generateNarrative(rootId),
  };
}

// ── Fetch ─────────────────────────────────────────────

async function pikFetch<T>(path: string): Promise<T> {
  const resp = await fetch(`${PIK_BASE}${path}`, { headers: { 'Accept': 'application/json' } });
  if (!resp.ok) throw new Error(`PIK ${resp.status}: ${path}`);
  const json = await resp.json();
  return (json.data ?? json) as T;
}

export async function fetchHeroes(): Promise<Hero[]> {
  const raw = await pikFetch<Record<string, unknown>[]>('/api/users');
  return raw.map(mapListRow);
}

export async function fetchHero(rootId: string): Promise<Hero> {
  const raw = await pikFetch<Record<string, unknown>>(`/api/users/${rootId}`);
  return mapFullUser(raw);
}

export async function fetchLeaderboard(): Promise<LeaderboardEntry[]> {
  const raw = await pikFetch<Record<string, unknown>[]>('/api/users');
  return raw
    .map(r => ({
      rank: 0, root_id: r.root_id as string,
      display_name: (r.hero_name ?? 'Unknown') as string,
      alignment: ((r.fate_alignment as string) || 'NONE') as Alignment,
      value: (r.fate_xp ?? 0) as number,
      fate_level: (r.fate_level ?? 1) as number,
      sessions: (r.active_sources ?? 0) as number,
    }))
    .sort((a, b) => b.value - a.value)
    .map((e, i) => ({ ...e, rank: i + 1 }));
}

export function xpProgress(prog: Progression): number {
  const needed = prog.xp_to_next_level;
  if (!needed) return 1;
  return Math.min(1, Math.max(0, prog.xp_in_current_level / needed));
}

export const MODIFIER_LABEL: Record<string, string> = {
  xp_bonus_pct: 'XP Bonus', boss_damage_pct: 'Boss Dmg', luck_pct: 'Luck',
  defense: 'Defense', crit_pct: 'Crit', cooldown_pct: 'Cooldown', fate_affinity: 'Fate Affinity',
};

// ── Vault API ─────────────────────────────────────────
// Sprint 8: Cache opening, title equipping, gear equipping

/** Open a sealed Fate Cache — requires Bearer token */
export async function openFateCache(
  rootId: string,
  cacheId: string,
  token: string,
): Promise<{
  reward_type:  string;
  reward_value: string;
  display_name: string;
  rarity_tier:  Rarity;
  xp_granted?:  number;
  message?:     string;
}> {
  const res = await fetch(`${PIK_BASE}/api/users/${rootId}/caches/${cacheId}/open`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json?.message ?? 'Failed to open cache');
  return json?.data ?? json;
}

/** Equip a title — pass titleId = 'none' to remove */
export async function equipTitle(
  rootId: string,
  titleId: string,
  token: string,
): Promise<{ equipped_title: string | null; display_name?: string; message: string }> {
  const res = await fetch(`${PIK_BASE}/api/users/${rootId}/titles/${titleId}/equip`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json?.message ?? 'Failed to equip title');
  return json?.data ?? json;
}

/** Fetch all titles (earned + locked) for a hero — requires Bearer token */
export async function fetchTitles(
  rootId: string,
  token: string,
): Promise<Array<{
  title_id:     string;
  display_name: string;
  category:     string;
  description:  string | null;
  is_earned:    boolean;
  is_equipped:  boolean;
  granted_at:   string | null;
}>> {
  const res = await fetch(`${PIK_BASE}/api/users/${rootId}/titles`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json?.message ?? 'Failed to fetch titles');
  return json?.data ?? [];
}

/** Equip a gear item from inventory */
export async function equipGear(
  rootId: string,
  inventoryId: string,
  token: string,
): Promise<{ message: string }> {
  const res = await fetch(`${PIK_BASE}/api/users/${rootId}/gear/${inventoryId}/equip`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json?.message ?? 'Failed to equip gear');
  return json?.data ?? json;
}

// ── Mock ──────────────────────────────────────────────

export const MOCK_HEROES: Hero[] = [{
  root_id: 'mock-001', display_name: 'Aethon Brightforge', alignment: 'ORDER',
  account_type: 'registered', created_at: '2025-01-01T00:00:00Z',
  progression: {
    fate_level: 7, total_xp: 3200, xp_to_next_level: 500,
    xp_in_current_level: 200, sessions_completed: 14,
    fate_markers: ['Felt the threads of fate shift and realign', 'Claimed a trophy from a fallen guardian'],
    titles: [
      { title_id: 'title_fate_awakened', title_name: 'FATE AWAKENED', category: 'fate', granted_at: '2025-01-10T00:00:00Z', rarity: 'rare' },
      { title_id: 'title_veil_touched',  title_name: 'Veil Touched',  category: 'boss', granted_at: '2025-02-01T00:00:00Z', rarity: 'epic' },
    ],
    equipped_title: 'title_veil_touched',
  },
  gear: null, fate_caches: [],
  sources: [{ source_id: 'hv-001', source_name: "Heroes' Veritas — Venue 01", linked_at: '2025-01-01T00:00:00Z', is_active: true, scope: 'xp fate_markers titles' }],
  source_progression: [{ source_id: 'hv-001', source_name: "Heroes' Veritas — Venue 01", source_type: 'venue', sessions: 14, xp_contributed: 3200, boss_kills: 8, best_boss_pct: 80, caches_granted: 12, gear_acquired: 5, first_activity: '2025-01-01T00:00:00Z', last_activity: '2025-03-01T00:00:00Z' }],
  wearable: null,
  recent_events: [
    { event_id: 'e1', event_type: 'progression.xp_granted', payload: { xp: 150 }, changes: null, ts: '2025-03-05T10:00:00Z', source_id: 'hv-001' },
    { event_id: 'e2', event_type: 'loot.cache_opened', payload: { cache_type: 'boss_kill' }, changes: { reward_name: 'Ember Dirk', reward_rarity: 'uncommon' }, ts: '2025-03-04T18:35:00Z', source_id: 'hv-001' },
  ],
  narrative: generateNarrative('mock-001'),
}];
